#! /bin/bash
case $1 in
	start)	
		echo  ${_RED} Delete old iptables
		sudo iptables -t nat -F OUTPUT 
		sudo iptables -t nat -F REDSOCKS 
		sudo iptables -t nat -X REDSOCKS 
		#echo  ${_RED} Kill old ssh
		#sudo pkill ssh
		#echo  ${_GREEN} Start ssh
		echo  ${_RED} Kill old redsocks
		sudo pkill redsocks
		echo  ${_GREEN} Start redsocks
		sudo /usr/local/bin/redsocks -c /home/doubleleft/redsocks.conf
		echo  ${_GREEN} Start add chain iptables-nat-redsocks
		sudo iptables -t nat -N REDSOCKS
		sudo iptables -t nat -A REDSOCKS -d 0.0.0.0/8 -j RETURN
		sudo iptables -t nat -A REDSOCKS -d 10.0.0.0/8 -j RETURN
		sudo iptables -t nat -A REDSOCKS -d 127.0.0.0/8 -j RETURN
		sudo iptables -t nat -A REDSOCKS -d 169.254.0.0/16 -j RETURN
		sudo iptables -t nat -A REDSOCKS -d 172.16.0.0/12 -j RETURN
		sudo iptables -t nat -A REDSOCKS -d 192.168.0.0/16 -j RETURN
		sudo iptables -t nat -A REDSOCKS -d 224.0.0.0/4 -j RETURN
		sudo iptables -t nat -A REDSOCKS -d 240.0.0.0/4 -j RETURN
		#Anything else should be redirected to port 12345
		#sudo iptables -t nat -A REDSOCKS -p tcp -j REDIRECT --to-ports 12345
		sudo iptables -t nat -A REDSOCKS -p tcp -j DNAT --to 127.0.0.1:12345
		sudo iptables -t nat -A REDSOCKS -p udp -o eth0 -j DNAT --to 127.0.0.1:12345
		#sudo iptables -t nat -A REDSOCKS -p tcp -o wlan0 -j DNAT --to 127.0.0.1:12345
		#sudo iptables -t nat -A REDSOCKS -p udp -o wlan0 -j DNAT --to 127.0.0.1:12345

		#sudo iptables -t nat -A OUTPUT -p tcp -j REDSOCKS --to 127.0.0.1:12345
		sudo iptables -t nat -A OUTPUT -p tcp -j REDSOCKS
		#sudo iptables -t nat -A OUTPUT -p udp -j REDSOCKS
		#sudo iptables -t nat -A OUTPUT -p icmp -j REDSOCKS
		# Any tcp connection made by `luser' should be redirected.
		#iptables -t nat -A OUTPUT -p tcp -m owner --uid-owner luser -j REDSOCKS
		
		# You can also control that in more precise way using `gid-owner` from
		# iptables.
		#groupadd socksified
		#usermod --append --groups socksified luser
		#iptables -t nat -A OUTPUT -p tcp -m owner --gid-owner socksified -j REDSOCKS

		# Now you can launch your specific application with GID `socksified` and it
		# will be... socksified. See following commands (numbers may vary).
		# Note: you may have to relogin to apply `usermod` changes.
		#luser$ id
		#uid=1000(luser) gid=1000(luser) groups=1000(luser),1001(socksified)
		#luser$ sg socksified -c id
		#uid=1000(luser) gid=1001(socksified) groups=1000(luser),1001(socksified)
		#luser$ sg socksified -c "firefox"
		;;
	stop)
		echo  ${_RED} Kill old ssh
		sudo pkill ssh
		echo  ${_RED} Kill redsocks
		sudo pkill redsocks
		echo  ${_RED} Delete iptables
		sudo iptables -t nat -F OUTPUT 
		sudo iptables -t nat -F REDSOCKS 
		sudo iptables -t nat -X REDSOCKS 
		echo  ${_green} iptables REDSOCKS stop
		;;
esac
